[tool.bumpversion]
current_version = "1.4.1"
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "custom_components/bakalari/manifest.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'


[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
no-regex = true

[[tool.bumpversion.files]]
filename = "custom_components/bakalari/const.py"
search = 'LIB_VERSION: Final = "{current_version}"'
replace = 'LIB_VERSION: Final = "{new_version}"'
